quote_column: "EndOfDayQuote ExchangeOfficialClose"
buffer_day: 90
calc_days: [5, 10, 20, 40, 60]
lag_days: [1, 2, 3, 4, 5, 10, 20, 40, 60]
fin_columns:
  - "Result_FinancialStatement FiscalYear"
  - "Result_FinancialStatement NetSales"
  - "Result_FinancialStatement OperatingIncome"
  - "Result_FinancialStatement OrdinaryIncome"
  - "Result_FinancialStatement NetIncome"
  - "Result_FinancialStatement TotalAssets"
  - "Result_FinancialStatement NetAssets"
  - "Result_FinancialStatement CashFlowsFromOperatingActivities"
  - "Result_FinancialStatement CashFlowsFromFinancingActivities"
  - "Result_FinancialStatement CashFlowsFromInvestingActivities"
  - "Forecast_FinancialStatement FiscalYear"
  - "Forecast_FinancialStatement NetSales"
  - "Forecast_FinancialStatement OperatingIncome"
  - "Forecast_FinancialStatement OrdinaryIncome"
  - "Forecast_FinancialStatement NetIncome"
  - "Result_Dividend FiscalYear"
  - "Result_Dividend QuarterlyDividendPerShare"
  - "Result_Dividend AnnualDividendPerShare"
  - "Forecast_Dividend FiscalYear"
  - "Forecast_Dividend QuarterlyDividendPerShare"
  - "Forecast_Dividend AnnualDividendPerShare"
