name: Python

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Lint
        run: ./hack/lint_workflow.sh
